cmake_minimum_required(VERSION 3.14 FATAL_ERROR)
project(Sabbath LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 23)
add_subdirectory(external)
add_executable(Sabbath Sabbath.cpp)
find_package(PostgreSQL)
target_link_libraries(Sabbath PostgreSQL::PostgreSQL)
target_link_libraries(Sabbath uWebSockets)
